### ISSUE TITLE
Theme changes "Sass" file syntax to uppercase -> Emmet stop work

### ISSUE THREAD

**Issue by itslooklike** [Miw0/SoDaReloaded-Theme#24]
Hello and thanks for the great theme!
After installed, the theme from packagecontrol (even without activating it), in Sublime "Sass" file syntax has become automatically change to "SASS" (uppercase), because of this, Emmet ceased to function properly.
![2](https://cloud.githubusercontent.com/assets/17547664/15274408/20194228-1ab9-11e6-9fb3-3941b2368df6.jpg)

**Comment by michael-jahn-dev** [comment]
Hmm this sounds weird, I'm gonna change the Name of "SASS" syntax to "Sass" which is more correct anyway regarding their typo on http://sass-lang.com/. Could you tell me if this does fix that for you?

**Comment by itslooklike** [comment]
Did not help. When I open ".sass" file in syntax menu "Sass" is NOT selected.
But if I put it by hand, Emmet start work correct.
![2](https://cloud.githubusercontent.com/assets/17547664/15338075/fdc56ea2-1c86-11e6-83d1-4122e760226e.jpg)

**Comment by michael-jahn-dev** [comment]
@itslooklike and you say it works without any problems when you uninstall this theme? I cannot imagine why this theme should mess up with your Sass syntax, especially if it isn't activated. Do you have any Sass plugins installed?

See like for me, I have this theme also installed, but not activated because I am using another theme currently and my SCSS files are working flawlessly.

**Comment by itslooklike** [comment]
for syntax highlighting I use https://packagecontrol.io/packages/Sass

Yes, immediately after removing, the problem is solved.
I feel that after installation, the syntax style changes to any custom that do not coincide with Sublime.

You can try to reproduce the problem, simply create a "style.sass", select it and type "db + tab", you will see a ";" following the rules.

PS: "auto_complete": false - must be in user settings.

**Comment by michael-jahn-dev** [comment]
Okay I see. Since I don't know any solution for this I'm gonna remove the syntax files like Sass, Less, SCSS, etc. and only keep the syntax files for things like bower.json etc. because packages like the Sass package mostly include their own syntax file definitions so there is no need for this theme to override them and possibly produce bugs _even_ when the theme isn't actived at all. This might be a bug related to Sublime Text itself, which seem to read and apply syntax files even if the package isn't activated.
