### ISSUE TITLE
Autowidth tabs clip italic titles

### ISSUE THREAD

**Issue by scottmatthewman** [Miw0/SoDaReloaded-Theme#25]
Congrats on the new theme build!

I noticed that when using `soda_tabs_autowidth` set to `true`, tabs with italic text (e.g., those created when the `preview_on_click` option is set to the default of `true`), the right hand edge of the italic text is clipped slightly. Example (zoomed to 200%):

![screenshot 2016-05-25 09 56 30](https://cloud.githubusercontent.com/assets/18256/15534176/8acdc8f2-225f-11e6-995b-91287af5525b.png)

**Comment by michael-jahn-dev** [comment]
Hey @scottmatthewman :)

I will look into this as soon as possible, thanks for reporting!

**Comment by michael-jahn-dev** [comment]
Hm the issue is that when `soda_tabs_autowidth` is set to `true` the setting `tab_width` is set to `0`. This controls the min-width of one tab. I am testing on Windows and for me everything is fine. This seems to be coming from Mac OS X font anti-aliasing which renders the fonts bolder than on Windows. 

I don't know really what to do here other than setting `tab_width` to a value greater than zero which might be not the best solution since your example seems to be about 105px wide so the best setting for your case would be ~106px but as you might understand I shouldn't set this for one test case only..
