### ISSUE TITLE
Error message when opening Sublime Text

### ISSUE THREAD

**Issue by schuette** [Miw0/SoDaReloaded-Theme#26]
Getting this error this morning after the Package Control update:

Error loading syntax file "Packages/Theme - SoDaReloaded/light/icons/Langs/SCSS.tmLanguage": Unable to open Packages/Theme - SoDaReloaded/light/icons/Langs/SCSS.tmLanguage

I've restarted multiple times, still getting error. Any ideas?

**Comment by michael-jahn-dev** [comment]
Yes, I deleted the Sass syntax definitions recently because they made problems with Emmet etc. 

To fix your issue you must set the Syntax again for SCSS files under `View > Syntax > Open all with current extension as .. > SCSS` where `SCSS` is your Sass package which you installed to get Sass support into Sublime Text. 

I hope I could help you and sorry for the unpleasantness. 

Von meinem iPhone gesendet

**Comment by schuette** [comment]
Ok thanks! I got it working now. I also uninstalled from package control and reinstalled and that fixed it.

**Comment by michael-jahn-dev** [comment]
Glad to hear that it works now! :)

Von meinem iPhone gesendet
