### ISSUE TITLE
Disables half of Sublime plugins

### ISSUE THREAD

**Issue by ghost** [Miw0/SoDaReloaded-Theme#33]
Healthy Sublime is all about Internet. So it goes for plugin **Miw0/SoDaReloaded**. Asian software is mostly malware in the Americas, of late. From what I understand, living in 3rd world (Region 3 Americas), Region 2 Asia has some nation states that practice extreme censorship. North Korea and China being 2 well-known examples. Kudos to MiW0 for trying to build anything global behind The Great Wall. **_SoDaReloaded resolution struggles with more than that_**. For one thing, mine is a 3rd world install. Trump damage to 3rd world global trade cannot be good for 3rd world Internet. England being 98.7+ trillion in the gutter (2014 and counting, as Trump and Her Majesty strolled out of Buckingham Palace with identical tans), **plugin streaming** for her colonies is a **_growing problem_**. Doing everything in today's new Internet-Of-Things. Miw0 should work with someone from Europe Region 1. Mainland Europe is on top of things. Especially, recently. I have found Sweden and Germany to be most helpful with apps and connectivity.

**Comment by tomm1996** [comment]
has anyone really been far even as decided to use even go want to do look more like

**Comment by ghost** [comment]
**_tomm1996_** [Tom McLean] That would be the problem. If the stream is not precisely calibrated, then the app (Sublime) cannot structure itself around the plugin delivery... Once delivery is normalized, then perfecting of the app code can proceed with desktop precision.

We all struggle with packet malformation, every day stripping software and reinstalling OS. Node 78, California at 11ms- is particularly destructive (and so-cautions users). Open Source Sublime is always the first victim. Miw0, Trump and his boss the Queen, are not the culture to blame. Above noted region’s Network Engineers do work around the issues. Need a contact life-line? This post is not SPAM. If you know how to install this plugin that is effected by packet-loss, post a reply.

**Comment by michael-jahn-dev** [comment]
Closing this for spam. Sorry.

**Comment by anyotherway** [comment]
Worm, 
Your interest is ‘interesting’. My post is not SPAM, rather highlighting a critical issue that impacts package development and Sublime usability. I am concerned that you may think global security paradigms are inconsequential. Please read carefully, and contribute with to the post with replies concerning connectivity.

Using Sublime to develop a circular menu app with STU at CSS-PLAY, we noted aberrations, discussed in the thread that concerns you. Engineers in Germany (2) and Sweden (1) stabilize Sublime and make progress possible in the development of apps, otherwise scuttled by app instability. 

It is obvious that packet loss is not an issue in Europe, and likely our 3rd world issues with the plugin do not exist there. However, we should then consider why critical connectivity issues are ignored.

Debt in England is viewed by Europeans in a way that precludes correction of the node problems here, In 3rd world Americas. Who cares ‘why’, but it is helpful to know that England and ALL of its colonies are not only at risk, but suffering. Developer workaround as identified solution, provided in my post.

Trump, obviously an aristocratic Royalty puppet is not going to do anything for the colony damaged by NSA (not mentioned for SPAM reasons). He is actively damaging colony technology relationships. Solution MUST lie outside of networks that fall under his Royal Dominion (in the real world, Worm, not America the free brain-wipe world, the only connected world). Solution provided in my post.

It will also be of interest to you that Wikipedia has first United States, and now all English colonies stated as “Region I”. Challenge anyone to undo his hack (not mine, I just typed it in). I did that with a hacker known in the Dark Web as “Hacker”, currently assisting law enforcement. The hack was reviewed and approved by NSA #2 director. 

That is the world we live in. It is not SPAM, as you mistakenly term it. It is a problem we ALL heave to work around. Enough of us hit on Europe for help, and they may realize that it is “no problem” for them to help us develop without constant, irritating packet loss.

That said, you should know. VPN is not a mandatory device component, but it is now mandatory Internet Service provision. Provision deployment in the absence of a Security Node, is nonsensical. My ISP has burned out 2 cable boxes and 3 modems, trying to comply. It is not just Sublime having problems. 

My concern is that Sublime will flop as malware. European packet processing is a critical solution for a problem that locally (in the third world) is not going away any time soon. 

Install SoDaReloaded, Sublime crashes. Reinstall OS X and Sublime, install SoDaReloaded, Sublime crashes. Review SoDaReloaded code cannot se problems, but network log shows packet problems. Your conclusion is everyone’s conclusion. Final test, Sublime crashes again (both ST2 and ST3 tested, both crash).

So. Rather than declare I am SPAM, how about a real solution. 

On 2017 Jun 13, at 1343 PM, Michael Worm <notifications@github.com> wrote:

Closing this for spam. Sorry.

**Comment by michael-jahn-dev** [comment]
Seems like we were having a misunderstanding. I did not really understand what you were trying to tell me about what your issue really is. That's why I closed it and marked it as spam.
